characters = {
    "Albedo": {"element": "Geo", "weapon": "Sword", "role": "Sub DPS", "region": "Mondstadt", "score": 3},
    "Arataki Itto": {"element": "Geo", "weapon": "Claymore", "role": "Main DPS", "region": "Inazuma", "score": 6},
    "Alhaitham": {"element": "Dendro", "weapon": "Sword", "role": "Main DPS", "region": "Sumeru", "score": 8},
    "Amber": {"element": "Pyro", "weapon": "Bow", "role": "Support", "region": "Mondstadt", "score": 3},
    "Arlecchino": {"element": "Pyro", "weapon": "Polearm", "role": "Main DPS", "region": "Fontaine", "score": 9},
    "Baizhu": {"element": "Dendro", "weapon": "Catalyst", "role": "Support", "region": "Liyue", "score": 8},
    "Barbara": {"element": "Hydro", "weapon": "Catalyst", "role": "Support", "region": "Mondstadt", "score": 2},
    "Beidou": {"element": "Electro", "weapon": "Claymore", "role": "Sub DPS", "region": "Liyue", "score": 4},
    "Bennett": {"element": "Pyro", "weapon": "Sword", "role": "Support", "region": "Mondstadt", "score": 10},
    "Candace": {"element": "Hydro", "weapon": "Polearm", "role": "Support", "region": "Sumeru", "score": 5},
    "Charlotte": {"element": "Cryo", "weapon": "Catalyst", "role": "Support", "region": "Fontaine", "score": 5},
    "Chasca": {"element": "Anemo", "weapon": "Bow", "role": "Main DPS", "region": "Sumeru", "score": 8},
    "Chevreuse": {"element": "Pyro", "weapon": "Polearm", "role": "Support", "region": "Fontaine", "score": 8},
    "Chiori": {"element": "Geo", "weapon": "Sword", "role": "Sub DPS", "region": "Inazuma", "score": 6},
    "Chongyun": {"element": "Cryo", "weapon": "Claymore", "role": "Sub DPS", "region": "Liyue", "score": 3},
    "Citlali": {"element": "Cryo", "weapon": "Catalyst", "role": "Support", "region": "Natlan", "score": 9},
    "Clorinde": {"element": "Electro", "weapon": "Sword", "role": "Main DPS", "region": "Fontaine", "score": 8},
    "Collei": {"element": "Dendro", "weapon": "Bow", "role": "Support", "region": "Sumeru", "score": 5},
    "Cyno": {"element": "Electro", "weapon": "Polearm", "role": "Main DPS", "region": "Sumeru", "score": 5},
    "Dahlia": {"element": "Hydro", "weapon": "Sword", "role": "Support", "region": "Mondstadt", "score": 4},
    "Dehya": {"element": "Pyro", "weapon": "Claymore", "role": "Support", "region": "Sumeru", "score": 2},
    "Diluc": {"element": "Pyro", "weapon": "Claymore", "role": "Main DPS", "region": "Mondstadt", "score": 5},
    "Diona": {"element": "Cryo", "weapon": "Bow", "role": "Support", "region": "Mondstadt", "score": 4},
    "Emilie": {"element": "Cryo", "weapon": "Catalyst", "role": "Support", "region": "Fontaine", "score": 7},
    "Eula": {"element": "Physical", "weapon": "Claymore", "role": "Main DPS", "region": "Mondstadt", "score": 3},
    "Faruzan": {"element": "Anemo", "weapon": "Bow", "role": "Support", "region": "Sumeru", "score": 7},
    "Fischl": {"element": "Electro", "weapon": "Bow", "role": "Sub DPS", "region": "Mondstadt", "score": 8},
    "Freminet": {"element": "Cryo", "weapon": "Claymore", "role": "Main DPS", "region": "Fontaine", "score": 4},
    "Furina": {"element": "Hydro", "weapon": "Sword", "role": "Support", "region": "Fontaine", "score": 10},
    "Ganyu": {"element": "Cryo", "weapon": "Bow", "role": "Main DPS", "region": "Liyue", "score": 5},
    "Gorou": {"element": "Geo", "weapon": "Bow", "role": "Support", "region": "Inazuma", "score": 5},
    "Hu Tao": {"element": "Pyro", "weapon": "Polearm", "role": "Main DPS", "region": "Liyue", "score": 7},
    "Ineffa": {"element": "Electro", "weapon": "Polearm", "role": "Sub DPS", "region": "Nod-Krai", "score": 8},
    "Iansan": {"element": "Anemo", "weapon": "Polearm", "role": "Support", "region": "Natlan", "score": 9},
    "Ifa": {"element": "Geo", "weapon": "Sword", "role": "Sub DPS", "region": "Natlan", "score": 3},
    "Jean": {"element": "Anemo", "weapon": "Sword", "role": "Support", "region": "Mondstadt", "score": 5},
    "Kachina": {"element": "Hydro", "weapon": "Sword", "role": "Support", "region": "Natlan", "score": 3},
    "Kaedehara Kazuha": {"element": "Anemo", "weapon": "Sword", "role": "Support", "region": "Inazuma", "score": 8},
    "Kaeya": {"element": "Cryo", "weapon": "Sword", "role": "Sub DPS", "region": "Mondstadt", "score": 5},
    "Kamisato Ayaka": {"element": "Cryo", "weapon": "Sword", "role": "Main DPS", "region": "Inazuma", "score": 6},
    "Kamisato Ayato": {"element": "Hydro", "weapon": "Sword", "role": "Main DPS", "region": "Inazuma", "score": 4},
    "Kaveh": {"element": "Dendro", "weapon": "Sword", "role": "Support", "region": "Sumeru", "score": 2},
    "Keqing": {"element": "Electro", "weapon": "Sword", "role": "Main DPS", "region": "Liyue", "score": 5},
    "Kinich": {"element": "Geo", "weapon": "Sword", "role": "Main DPS", "region": "Natlan", "score": 8},
    "Kirara": {"element": "Dendro", "weapon": "Sword", "role": "Support", "region": "Sumeru", "score": 5},
    "Klee": {"element": "Pyro", "weapon": "Catalyst", "role": "Main DPS", "region": "Mondstadt", "score": 4},
    "Kujou Sara": {"element": "Electro", "weapon": "Bow", "role": "Support", "region": "Inazuma", "score": 4},
    "Kuki Shinobu": {"element": "Electro", "weapon": "Sword", "role": "Support", "region": "Inazuma", "score": 3},
    "Lan Yan": {"element": "Geo", "weapon": "Sword", "role": "Main DPS", "region": "Liyue", "score": 7},
    "Layla": {"element": "Cryo", "weapon": "Sword", "role": "Support", "region": "Sumeru", "score": 5},
    "Lisa": {"element": "Electro", "weapon": "Catalyst", "role": "Support", "region": "Mondstadt", "score": 4},
    "Lynette": {"element": "Anemo", "weapon": "Sword", "role": "Support", "region": "Fontaine", "score": 4},
    "Lyney": {"element": "Pyro", "weapon": "Bow", "role": "Main DPS", "region": "Fontaine", "score": 7},
    "Mavuika": {"element": "Hydro", "weapon": "Sword", "role": "Main DPS", "region": "Natlan", "score": 10},
    "Mika": {"element": "Cryo", "weapon": "Polearm", "role": "Support", "region": "Mondstadt", "score": 3},
    "Mona": {"element": "Hydro", "weapon": "Catalyst", "role": "Support", "region": "Mondstadt", "score": 5},
    "Mualani": {"element": "Hydro", "weapon": "Sword", "role": "Main DPS", "region": "Natlan", "score": 8},
    "Nahida": {"element": "Dendro", "weapon": "Catalyst", "role": "Support", "region": "Sumeru", "score": 9},
    "Navia": {"element": "Geo", "weapon": "Claymore", "role": "Main DPS", "region": "Fontaine", "score": 8},
    "Neuvillette": {"element": "Hydro", "weapon": "Catalyst", "role": "Main DPS", "region": "Fontaine", "score": 10},
    "Nilou": {"element": "Hydro", "weapon": "Sword", "role": "Main DPS", "region": "Sumeru", "score": 2},
    "Ningguang": {"element": "Geo", "weapon": "Catalyst", "role": "Sub DPS", "region": "Liyue", "score": 4},
    "Noelle": {"element": "Geo", "weapon": "Claymore", "role": "Support", "region": "Mondstadt", "score": 5},
    "Ororon": {"element": "Hydro", "weapon": "Polearm", "role": "Support", "region": "Natlan", "score": 7},
    "Qiqi": {"element": "Cryo", "weapon": "Sword", "role": "Support", "region": "Liyue", "score": 2},
    "Raiden Shogun": {"element": "Electro", "weapon": "Polearm", "role": "Main DPS", "region": "Inazuma", "score": 7},
    "Razor": {"element": "Electro", "weapon": "Claymore", "role": "Main DPS", "region": "Mondstadt", "score": 3},
    "Rosaria": {"element": "Cryo", "weapon": "Polearm", "role": "Sub DPS", "region": "Mondstadt", "score": 5},
    "Sayu": {"element": "Anemo", "weapon": "Claymore", "role": "Support", "region": "Inazuma", "score": 4},
    "Sethos": {"element": "Electro", "weapon": "Bow", "role": "Main DPS", "region": "Sumeru", "score": 4},
    "Shenhe": {"element": "Cryo", "weapon": "Polearm", "role": "Support", "region": "Liyue", "score": 7},
    "Skirk": {"element": "Electro", "weapon": "Polearm", "role": "Main DPS", "region": "???", "score": 9},
    "Tartaglia": {"element": "Hydro", "weapon": "Bow", "role": "Main DPS", "region": "Liyue", "score": 5},
    "Thoma": {"element": "Pyro", "weapon": "Polearm", "role": "Support", "region": "Inazuma", "score": 4},
    "Tighnari": {"element": "Dendro", "weapon": "Bow", "role": "Main DPS", "region": "Sumeru", "score": 6},
    "Traveler (Anemo)": {"element": "Anemo", "weapon": "Sword", "role": "Support", "region": "???", "score": 4},
    "Traveler (Dendro)": {"element": "Dendro", "weapon": "Sword", "role": "Support", "region": "???", "score": 6},
    "Traveler (Electro)": {"element": "Electro", "weapon": "Sword", "role": "Support", "region": "???", "score": 1},
    "Traveler (Geo)": {"element": "Geo", "weapon": "Sword", "role": "Support", "region": "???", "score": 3},
    "Traveler (Pyro)": {"element": "Pyro", "weapon": "Sword", "role": "Support", "region": "Natlan", "score": 6},
    "Varesa": {"element": "Hydro", "weapon": "Sword", "role": "Main DPS", "region": "Natlan", "score": 9},
    "Venti": {"element": "Anemo", "weapon": "Bow", "role": "Support", "region": "Mondstadt", "score": 4},
    "Wanderer": {"element": "Anemo", "weapon": "Catalyst", "role": "Main DPS", "region": "Sumeru", "score": 6},
    "Wriothesley": {"element": "Cryo", "weapon": "Catalyst", "role": "Main DPS", "region": "Fontaine", "score": 7},
    "Xiangling": {"element": "Pyro", "weapon": "Polearm", "role": "Sub DPS", "region": "Liyue", "score": 9},
    "Xianyun": {"element": "Anemo", "weapon": "Catalyst", "role": "Support", "region": "Liyue", "score": 8},
    "Xiao": {"element": "Anemo", "weapon": "Polearm", "role": "Main DPS", "region": "Liyue", "score": 8},
    "Xilonen": {"element": "Geo", "weapon": "Catalyst", "role": "Support", "region": "Natlan", "score": 9},
    "Xingqiu": {"element": "Hydro", "weapon": "Sword", "role": "Sub DPS", "region": "Liyue", "score": 8},
    "Yae Miko": {"element": "Electro", "weapon": "Catalyst", "role": "Sub DPS", "region": "Inazuma", "score": 6},
    "Yanfei": {"element": "Pyro", "weapon": "Catalyst", "role": "Main DPS", "region": "Liyue", "score": 4},
    "Yaoyao": {"element": "Dendro", "weapon": "Polearm", "role": "Support", "region": "Sumeru", "score": 6},
    "Yelan": {"element": "Hydro", "weapon": "Bow", "role": "Sub DPS", "region": "Liyue", "score": 9},
    "Yoimiya": {"element": "Pyro", "weapon": "Bow", "role": "Main DPS", "region": "Inazuma", "score": 5},
    "Yumemizuki Mizuki": {"element": "Anemo", "weapon": "Catalyst", "role": "Support", "region": "Inazuma", "score": 3},
    "Yun Jin": {"element": "Geo", "weapon": "Polearm", "role": "Support", "region": "Liyue", "score": 5},
    "Zhongli": {"element": "Geo", "weapon": "Polearm", "role": "Support", "region": "Liyue", "score": 7}
}