diff1 = [
    "the", "and", "for", "are", "but", "not", "you", "all", "can", "had", 
    "was", "her", "one", "our", "out", "day", "get", "has", "him", "his", 
    "how", "man", "new", "now", "old", "see", "two", "way", "who", "boy", 
    "did", "its", "let", "put", "say", "she", "too", "use", "that", "with", 
    "this", "have", "from", "they", "word", "what", "your", "when", "make", 
    "time", "will", "like", "them", "then", "some", "could", "first", "other", 
    "there", "their", "about", "which", "would", "write", "these", "thing", 
    "people", "water", "after", "where", "right", "sound", "little", "every", 
    "found", "still", "study", "great", "those", "always", "large", "might", 
    "house", "world", "place", "again", "under", "going", "such", "through", 
    "years", "much", "before", "line", "part", "more", "come", "most", "over", 
    "know", "than", "look", "here", "must", "back", "even", "good", "any", 
    "give", "well", "only", "very", "just", "help", "want", "because", "each", 
    "these", "those", "long", "down", "side", "been", "call", "may", "find", 
    "day", "did", "get", "come", "made", "may", "part", "over", "new", "sound", 
    "take", "only", "little", "work", "know", "place", "year", "live", "me", 
    "back", "give", "most", "very", "after", "thing", "our", "just", "name", 
    "sentence", "think", "say", "great", "where", "help", "through", "much", 
    "before", "line", "right", "too", "mean", "old", "any", "same", "tell", 
    "boy", "follow", "came", "want", "show", "also", "around", "form", "three", 
    "small", "set", "put", "end", "does", "another", "well", "large", "must", 
    "big", "even", "such", "because", "turn", "here", "why", "ask", "went", 
    "men", "read", "need", "land", "different", "home", "us", "move", "try", 
    "kind", "hand", "picture", "again", "change", "off", "play", "spell", "air"
]

diff2 = [
    "animal", "answer", "school", "father", "mother", "family", "letter", "second", 
    "friend", "enough", "across", "between", "number", "always", "something", 
    "thought", "country", "example", "children", "important", "different", "together", 
    "sometimes", "mountain", "started", "everything", "river", "carry", "state", 
    "book", "eye", "never", "start", "city", "earth", "light", "thought", "head", 
    "story", "left", "few", "group", "run", "really", "soon", "idea", "open", 
    "paper", "often", "until", "mile", "night", "walk", "white", "sea", "began", 
    "grow", "took", "river", "four", "carry", "state", "once", "hear", "stop", 
    "without", "later", "miss", "idea", "enough", "eat", "face", "watch", "far", 
    "Indian", "really", "almost", "let", "above", "girl", "sometimes", "mountain", 
    "young", "talk", "soon", "list", "song", "being", "leave", "family", "it's", 
    "body", "music", "color", "stand", "sun", "question", "fish", "area", "mark", 
    "dog", "horse", "birds", "problem", "complete", "room", "knew", "since", "ever", 
    "piece", "told", "usually", "didn't", "friends", "easy", "heard", "order", 
    "red", "door", "sure", "become", "top", "ship", "across", "today", "during", 
    "short", "better", "best", "low", "hour", "black", "products", "happened", 
    "whole", "measure", "remember", "early", "waves", "reached", "listen", "wind", 
    "rock", "space", "covered", "fast", "several", "hold", "himself", "toward", 
    "five", "step", "morning", "passed", "vowel", "true", "hundred", "against", 
    "pattern", "numeral", "table", "north", "slowly", "money", "map", "farm", 
    "pulled", "draw", "voice", "seen", "cold", "cried", "plan", "notice", "south", 
    "sing", "war", "ground", "fall", "king", "town", "I'll", "unit", "figure", 
    "certain", "field", "travel", "wood", "fire", "upon", "done", "English", 
    "road", "half", "ten", "fly", "gave", "box", "finally", "wait", "correct", 
    "oh", "quickly", "person", "became", "shown", "minutes", "strong", "verb", 
    "stars", "front", "feel", "fact", "inches", "street", "decided", "contain"
]

diff3 = [
    "government", "education", "information", "development", "management", 
    "technology", "community", "organization", "population", "environment", 
    "understand", "experience", "especially", "interesting", "important", 
    "different", "necessary", "beautiful", "direction", "production", 
    "discover", "describe", "determine", "represent", "introduce", 
    "opportunity", "possibility", "responsible", "significant", "traditional", 
    "condition", "decision", "position", "property", "question", 
    "television", "university", "generation", "communication", "application", 
    "attention", "collection", "expression", "instruction", "production", 
    "reaction", "situation", "solution", "adventure", "advantage", 
    "atmosphere", "character", "committee", "competition", "conclusion", 
    "confidence", "connection", "construction", "conversation", "description", 
    "difficulty", "electricity", "emergency", "equipment", "examination", 
    "experience", "experiment", "explanation", "following", "function", 
    "government", "happiness", "imagination", "importance", "improvement", 
    "information", "knowledge", "language", "management", "measurement", 
    "membership", "movement", "necessary", "operation", "organization", 
    "performance", "population", "possibility", "preparation", "production", 
    "protection", "punishment", "qualification", "reaction", "recognition", 
    "reference", "relation", "representative", "requirement", "resolution", 
    "restaurant", "satisfaction", "secretary", "selection", "situation", 
    "solution", "statement", "success", "suggestion", "temperature", 
    "tourist", "tradition", "transportation", "treatment", "understanding", 
    "university", "vacation", "vegetable", "vehicle", "volunteer", 
    "weather", "wedding", "weight", "welcome", "wilderness", "window", 
    "winter", "wonder", "wooden", "worker", "world", "writer", "yellow", 
    "yesterday", "young", "ability", "absence", "academic", "accident", 
    "account", "achievement", "acknowledge", "acquire", "activity", 
    "actually", "addition", "address", "administration", "advantage", 
    "advertisement", "advice", "affect", "afternoon", "agency", "agreement", 
    "airport", "alcohol", "although", "american", "analysis", "announce", 
    "annual", "answer", "anxious", "apartment", "appearance", "appliance", 
    "application", "appointment", "appreciate", "approach", "appropriate", 
    "approve", "argument", "arrange", "arrival", "article", "artist", 
    "assistant", "associate", "assume", "athlete", "attack", "attempt", 
    "attention", "attitude", "attractive", "audience", "authority", "available"
]

diff4 = [
    "accommodate", "accomplish", "acknowledgment", "approximately", 
    "architecture", "assessment", "association", "assumption", 
    "atmospheric", "characteristic", "collaboration", "commission", 
    "communication", "comprehensive", "concentration", "configuration", 
    "consciousness", "considerable", "conspiracy", "constitution", 
    "construction", "contemporary", "contribution", "conventional", 
    "cooperation", "coordinate", "corporation", "correspondence", 
    "demonstration", "development", "disappointment", "discrimination", 
    "distribution", "educational", "effectively", "environmental", 
    "establishment", "examination", "exceptionally", "experimental", 
    "extraordinary", "fundamental", "historically", "identification", 
    "implementation", "increasingly", "independent", "individuality", 
    "industrialized", "information", "infrastructure", "intelligence", 
    "intervention", "investigation", "manufacturing", "methodology", 
    "negotiation", "nevertheless", "observation", "occasionally", 
    "opportunity", "organization", "particularly", "participation", 
    "perception", "performance", "personality", "phenomenon", 
    "philosophical", "potentially", "precipitation", "preliminary", 
    "preparation", "prescription", "presentation", "presidential", 
    "probability", "professional", "proportional", "psychology", 
    "qualification", "recognition", "recommendation", "reflection", 
    "registration", "regulation", "relationship", "representative", 
    "requirement", "reservation", "resolution", "respectively", 
    "responsibility", "restaurant", "satisfaction", "significance", 
    "simultaneously", "sophisticated", "specifically", "substantial", 
    "sufficiently", "suggestion", "superintendent", "supervisor", 
    "suspicious", "technical", "technique", "technology", "temperature", 
    "tendency", "territory", "throughout", "transaction", "transformation", 
    "transition", "translation", "transmission", "transportation", 
    "understanding", "undertaking", "universally", "university", 
    "utilization", "valuation", "variation", "vegetable", "vehicle", 
    "volunteer", "vulnerable", "warranty", "wealthy", "weather", 
    "withdrawal", "workshop", "yesterday", "zoology", "abolition", 
    "aboriginal", "absorption", "abundance", "academic", "acceleration", 
    "acceptance", "accessibility", "accommodation", "accompaniment", 
    "accomplishment", "accountability", "accumulation", "achievement", 
    "acknowledgment", "acquisition", "adaptation", "additional", 
    "adjustment", "administration", "admiration", "admission", 
    "advancement", "advantageous", "advertisement", "advisability", 
    "aesthetic", "affectionate", "affiliation", "affirmative", 
    "aggregation", "agricultural", "allegation", "allocation", 
    "alternative", "amazement", "ambassador", "ambiguous", 
    "amplification", "anniversary", "announcement", "anticipation", 
    "appreciation", "approachable", "appropriation", "approximation"
]

diff5 = [
    "accommodation", "acknowledgment", "anthropology", "apprehension", 
    "archaeology", "architecture", "aristocracy", "articulate", 
    "assassination", "astonishment", "asymmetrical", "authoritarian", 
    "belligerent", "benevolence", "biochemistry", "bureaucracy", 
    "capitalism", "catastrophe", "characteristic", "chauvinism", 
    "circumference", "collaboration", "commensurate", "commiserate", 
    "compatibility", "compensation", "competition", "comprehensive", 
    "conciliation", "condescending", "configuration", "conglomerate", 
    "conscientious", "consecutive", "consensus", "consequence", 
    "conservatory", "consideration", "consistency", "conspicuous", 
    "constituency", "constitution", "contamination", "contemporary", 
    "contradiction", "controversial", "conventional", "correspondence", 
    "counterfeit", "cryptography", "deforestation", "deliberation", 
    "democracy", "demonstration", "deprivation", "derivative", 
    "determination", "developmental", "differentiate", "disappointment", 
    "discrimination", "disinterested", "dissertation", "distinguishing", 
    "documentation", "ecclesiastical", "ecological", "economical", 
    "educational", "effectiveness", "egalitarian", "elaboration", 
    "electricity", "embarrassment", "embezzlement", "encapsulation", 
    "encyclopedia", "enlightenment", "entrepreneur", "environmental", 
    "epidemiology", "epistemology", "equilibrium", "establishment", 
    "eucalyptus", "evaluation", "exaggeration", "exasperation", 
    "exceptional", "exclusionary", "exhibitionist", "existential", 
    "expeditionary", "experimentation", "exploitation", "extraordinary", 
    "facilitation", "fundamentalist", "galvanization", "generalization", 
    "geopolitical", "hallucination", "heterogeneous", "hippopotamus", 
    "historical", "hypothetical", "identification", "ideological", 
    "illegitimate", "illumination", "imagination", "immigration", 
    "impartiality", "implementation", "inadvertently", "incomprehensible", 
    "inconsequential", "incorporation", "independence", "indispensable", 
    "individuality", "inexplicable", "infrastructure", "inheritance", 
    "innocuous", "insignificant", "instability", "institutional", 
    "instrumental", "insurrection", "intelligence", "interchangeable", 
    "interdisciplinary", "interpretation", "interrogation", "intervention", 
    "intoxication", "investigation", "iridescent", "irresponsible", 
    "jurisdiction", "justification", "laboratory", "legitimacy", 
    "libertarian", "magnificent", "maintenance", "manipulation", 
    "manufacturing", "marginalization", "mathematics", "melodramatic", 
    "metamorphosis", "methodology", "mischievous", "miscellaneous", 
    "misinterpretation", "multifaceted", "negotiation", "neurological", 
    "nevertheless", "nonchalantly", "nonsensical", "nostalgia", 
    "obliteration", "obsolescence", "obstruction", "occupational", 
    "onomatopoeia", "opportunistic", "organization", "orientation", 
    "orthopedic", "outrageous", "overwhelming", "paleontology", 
    "paradoxical", "parliamentary", "participation", "pedestrian", 
    "perpendicular", "perseverance", "personification", "phenomenon", 
    "philosophical", "photosynthesis", "politician", "predicament", 
    "prestigious", "procrastination", "prognostication", "pronunciation", 
    "proportional", "proposition", "protagonist", "psychiatric", 
    "qualification", "quantitative", "questionnaire", "rationale", 
    "reconciliation", "rehabilitation", "renaissance", "repetition", 
    "representation", "resurrection", "retrospective", "revolutionary", 
    "sanctimonious", "schizophrenia", "simultaneously", "sophisticated", 
    "sovereignty", "specification", "stereotypical", "subterranean", 
    "superfluous", "superintendent", "supernatural", "susceptible", 
    "suspicious", "symmetrical", "technological", "temperamental", 
    "territorial", "theoretical", "traditionally", "transcendental", 
    "transformation", "transgression", "transparency", "tremendous", 
    "typographical", "unconditional", "underestimate", "understanding", 
    "undertaking", "unforgettable", "unilateral", "unprecedented", 
    "utilitarian", "vulnerability", "whimsical", "wonderful", "xenophobia", 
    "zoological"
]